CREATE DATABASE DB_FRAMAFOOD;
GO
USE DB_FRAMAFOOD;
GO
CREATE TABLE ROLES(-- 'ADMINISTRADOR', 'MESERA', 'CHEF', 'CAJERA'
IDROL       INT PRIMARY KEY IDENTITY(1,1)  NOT NULL,
NOMBRE      VARCHAR(50) NOT NULL
);

INSERT INTO ROLES VALUES('ADMINISTRADOR');
INSERT INTO ROLES VALUES('MESERA');
INSERT INTO ROLES VALUES('CHEF');
INSERT INTO ROLES VALUES('CAJERA');

GO
CREATE TABLE USUARIOS (
    IDUSUARIO         INT PRIMARY KEY IDENTITY(1,1),
	IDROL             INT NOT NULL,
    NOMBRE            VARCHAR(100) NOT NULL,
    USUARIOLOGIN      VARCHAR(50) NOT NULL,
    CONTRASENA        VARCHAR(255) NOT NULL, 
    ESTADO            BIT NOT NULL DEFAULT 1,
	CONSTRAINT FK_ROL_USU FOREIGN KEY(IDROL) REFERENCES ROLES(IDROL) 
);
GO

CREATE UNIQUE INDEX INU_USU_USULOGIN
ON USUARIOS (USUARIOLOGIN);

GO
CREATE TABLE MESAS (
    IDMESA          INT PRIMARY KEY IDENTITY(1,1),
    NUMERO          VARCHAR(5) NOT NULL,
	CANTIDAD_SILLA  INT NOT NULL,
    ESTADO          CHAR(3) NOT NULL, 
	CONSTRAINT CK_ESTADO_MESA CHECK (ESTADO IN('DIS','OCU','ESC'))-- 'DISPONIBLE', 'OCUPADA', ESPERA CUENTA
);
GO

CREATE UNIQUE INDEX INU_MES_NUM
ON MESAS (NUMERO);

GO
CREATE TABLE PLATOS (
    IDPLATO        INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE         VARCHAR(100) NOT NULL,
    DESCRIPCION    VARCHAR(500) NOT NULL,
    PRECIO         DECIMAL(10,2) NOT NULL,
    CATEGORIA      CHAR(3)    NOT NULL,
	CONSTRAINT CK_CAT_PLAT CHECK (CATEGORIA IN('COM','BEB','POS'))-- 'COMIDA', 'BEBIDA', POSTRES
);
GO
CREATE TABLE RECETAS (
    IDRECETA      INT PRIMARY KEY IDENTITY(1,1),
    IDPLATO       INT  NOT NULL,
    INSTRUCCIONES VARCHAR(1000) NOT NULL,
	CONSTRAINT FK_REC_PLA FOREIGN KEY (IDPLATO) REFERENCES PLATOS(IDPLATO)
);
GO
CREATE TABLE PEDIDOS (
    IDPEDIDO     INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    IDMESA       INT NOT NULL,
    IDMESERA     INT NOT NULL,
    FECHAHORA    DATETIME NOT NULL DEFAULT GETDATE(),
    ESTADO       CHAR(4) NOT NULL,
	CONSTRAINT CK_PED_EST CHECK (ESTADO IN('PEND','PREP','LIST')),-- 'PENDIENTE', 'EN PREPARACIÓN', 'LISTO', ETC.
	CONSTRAINT FK_MESA_PED FOREIGN KEY (IDMESA) REFERENCES MESAS(IDMESA),
	CONSTRAINT FK_MESERA_PED FOREIGN KEY(IDMESERA) REFERENCES USUARIOS(IDUSUARIO)
);
GO
CREATE TABLE DETALLEPEDIDO (
    IDDETALLE INT PRIMARY KEY IDENTITY(1,1),
    IDPEDIDO  INT NOT NULL,
    IDPLATO   INT NOT NULL,
	IDCHEF    INT NOT NULL,
    CANTIDAD  INT NOT NULL,
    ESTADO    CHAR(4) NOT NULL, 
	CONSTRAINT CK_DETPED_EST CHECK (ESTADO IN('COCI','LIST')),-- 'EN COCINA', 'LISTO', ETC.
	CONSTRAINT FK_DETPED_DET_PED  FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDOS(IDPEDIDO),
	CONSTRAINT FK_MESERA_DET_PED FOREIGN KEY (IDPLATO) REFERENCES PLATOS(IDPLATO),
	CONSTRAINT FK_CHEF_DET_PED FOREIGN KEY(IDCHEF) REFERENCES USUARIOS(IDUSUARIO)
);
GO
CREATE TABLE FACTURAS (
    IDFACTURA  INT PRIMARY KEY IDENTITY(1,1),
    IDPEDIDO   INT NOT NULL,
    IDCAJERA   INT NOT NULL,
    MONTOTOTAL DECIMAL(10,2) NOT NULL,
	FECHAHORA  DATETIME NOT NULL DEFAULT GETDATE(),
    METODOPAGO CHAR(3)  NOT NULL,
	CONSTRAINT CK_FACT_METO CHECK (METODOPAGO IN('EFE','TAR')),-- 'EFECTIVO', 'TARJETA'
	CONSTRAINT FK_PED_FACT FOREIGN KEY(IDPEDIDO) REFERENCES PEDIDOS(IDPEDIDO),
	CONSTRAINT FK_FACT_CAJ FOREIGN KEY(IDCAJERA) REFERENCES USUARIOS(IDUSUARIO)
);